### ISSUE TITLE
Tab should insert 4 spaces instead of switching focus

### ISSUE THREAD

**Issue by dons20** [mrmartineau/snippet-generator#1]
For coding purposes, tab is generally used to shift content, so please allow the Tab button to shift the content by 4 spaces or so.

**Comment by mrmartineau** [comment]
hi @dons20 , this is a good idea. I will add it to my to-do list.

**Comment by mrmartineau** [comment]
Hi @dons20, I have added basic tabbing support. have a look and let me know what you think. It needs improvement, but is workable at the moment.

**Comment by dons20** [comment]
Looks good so far! 
Also consider the following
* Allow the user to customize the tab length such as 2/4/8 (maybe via a dropdown?)
* Let Shift+Tab subtract the same number of tab spaces.

Aside from that, good stuff!
