### ISSUE TITLE
Atom slashes not working

### ISSUE THREAD

**Issue by flick36** [mrmartineau/snippet-generator#5]
Hi, just a little bug not yours, but Atom's snippet, thing is, the backslashes are not getting inserted as explained here: https://github.com/atom/snippets/issues/127 and, as the same post suggest you should replace the single

>  \\

 with four as in:

> \\\\\\\\

I don't know anything about React .-. but looking at the Code i think it's easily fixed by adding:

`.replace('\', '\\\\')` to the `props.snippet` in line 22 of `components/pre.js` but again, i don't know... Also, this is an ugly fix since it might not work if some snippet has some more than 1 backslash together but maybe with some regex it can be done ¿?

**Comment by mrmartineau** [comment]
Hi @flick36, thanks for reporting this. Does this not work because Atom actually has a bug?

Either way, I think I have fixed it, with this input:

```latex
\paragraph {
	${1:part name}
}

\label{
	part: ${1:part label}
}
$2
```
The generator produces this:

```latex
'.':
	'':
		'prefix': ''
		'body': """
			\\\\paragraph {
	${1:part name}
}

\\\\label{
	part: ${1:part label}
}
$2
		"""
```

I will not deploy it until you confirm that it is working as expected.

P.S. the `replace` method parameters I needed was actually: `.replace(/\\/gm, '\\\\\\\\')`

**Comment by flick36** [comment]
It's not a "bug" I think it's just the way `cson` works I'm not really sure tho, the output you shows seems correct, but at simply sight it looks like an ugly fix, because what happen if you have something like

```
\\paragraph {
	${1:part name}
}

\\label{
	part: ${1:part label}
}
$2
```
Will the output be something like:
```
'.':
	'':
		'prefix': ''
		'body': """
			\\\\\\\\paragraph {
	${1:part name}
}

\\\\\\\\label{
	part: ${1:part label}
}
$2
		"""
```
I can't really tested cause I'm not at home right now, but will try when I get there, but posting in case you can test it. I'll edit once I've tested if you haven't.

**Comment by mrmartineau** [comment]
@flick36 you are correct, if you have the input you suggested, with already escaped `cson`, my generator produces double the back slaches `\`, see below:

```latex
\\\\\\\\paragraph {
	${1:part name}
}

\\\\\\\\label{
	part: ${1:part label}
}
$2
```

This would then produce the correct amount of slashes when the snippet is expanded (`\\`). The snippet generator does not clean-up snippet code that already has escaped items, so it is best to clean it yourself beforehand. Hope that helps.

**Comment by flick36** [comment]
Then I think it's safe to deploy ;) and maybe put some note to clean it beforehand ?

**Comment by mrmartineau** [comment]
@flick36 thanks. I have deployed it now. Please take a look and let me know if anything needs to be fixed.
